import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import LeftNavbar from "../components/LeftNavbar";
import Content from "../components/Content";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex'>
        <LeftNavbar />
        <div className='w-full'>
          <Header />
          <Content />
        </div>
      </div>
    </div>
  );
};

export default Home;
